baseURL: https://ligato.io/
languageCode: en-us
title: Ligato
theme: hugo-fresh

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  navbarlogo:
    # Logo (from /images/logos/___)
    image: logos/ligato-navbar.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Ligato
    # Hero subtitle (optional)
    subtitle: An Open Source Go Framework for Building Applications to Control and Manage Cloud Native Network Functions (CNF)
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://docs.ligato.io/"
    # Hero image (from /images/___)
    image: ligato/ligato3.svg
    # Footer logos (from /images/logos/clients/___.svg)
    # Metz: replace client logos with FD.io, CNCF, K8S, Contiv VPP
    #clientlogos:
#    - grey-fdio
#    - kubernetes-seeklogo.com
#    - Go-Logo
#    - contiv-icon
#    - etcd
#    - nsm-grey
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Documentation
    url: "https://docs.ligato.io/"
  - title: Github
    sublinks:
    - title: CN Infra
      url: "https://github.com/ligato/cn-infra"
    - title: VPP Agent
      url: "https://github.com/ligato/vpp-agent"
    - title: All Repositories
      url: "https://github.com/ligato"
  - title: Presentations
    sublinks:
      - title: LFN Webinar - Building CNFs with FD.io & NSM
        url: https://www.youtube.com/watch?v=UcODeI-HVZE
      - title: Ligato Overview
        url: https://docs.google.com/presentation/d/1SlfBPgn3Uwi316OWU4-l0oQRSeqiLdmacnHcX0qNdxQ/present?usp=sharing
      - title: Ligato - A Platform for the Development of Cloud Native VNFs
        url: https://www.cisco.com/c/dam/m/en_us/network-intelligence/service-provider/digital-transformation/knowledge-network-webinars/pdfs/0530-techad-ckn.pdf
  - title: APIs
    sublinks:
      - title: VPP Agent REST API Doc
        url: https://docs.ligato.io/en/latest/api/api-vpp-agent/
      - title: VPP Agent OpenAPI Definitions
        url: https://app.swaggerhub.com/apis/chrisM9/ligato-vpp_agent_rest_ap_is/3
      - title: KV Scheduler REST API Doc
        url: https://docs.ligato.io/en/latest/api/api-kvs/
      - title: KV Scheduler OpenAPI Definitions
        url: https://app.swaggerhub.com/apis/chrisM9/ligato-kvs-rest-api/2-oas3
  - title: Community
    url: "/community/page"
#    sublinks:
#      - title: Community Page
#        url: "/community/page/"
  - title: Blog
    sublinks:
      - title: CNFs with a Dose of Ligato and FD.io/VPP
        url: "/blog/cnf-ligato-fdio"
  section1:
    title: Learn more about Ligato
    subtitle: CNFs and Development Features
    tiles:
    - title: What is a CNF?
      icon: mouse-globe
      text: Virtual Network Functions in Containers
      url: "cnf/cnf-def"
      buttonText: Learn More
    - title: Building Blocks
      icon: plug-cloud
      text: Plugins/Models/Protobufs for CNF development
      url: "architecture/lig-framework-overview"
      buttonText: Learn More
#    - title: Use Cases
#      icon: laptop-cloud
#      text: Solutions Using the Ligato VPP Agent
#      url: "use-cases/ligato-use-cases"
#      buttonText: Learn More
  section2:
    title: Rapid Innovation & Development
    subtitle: Packaging, Programming and Performance
    features:
    - title: Compact Footprint
      text: Packaged in Docker container together with VPP
      icon: laptop-globe3
    - title: Written in Golang
      text: Programming language for peformance and concurrency in cloud native environments
      icon: mouse-globe-sub
    - title: Key Value Datastores
      text: Fast, lightweight distribution of network configurations
      # Icon (from /images/illustrations/icons/___.svg)
      icon: database
    - title: Modular and Extensible
      text: Plugins for VPP, Linux, APIs, datastore, security, database systems
      icon: plug-cloud-new
    - title: Protobufs Data Structure
      text: Model-driven APIs; common transport
      icon: code
    - title: Configuration Scheduler
      text: Transaction-based for correct ordering, auto-healing, restarts
      icon: calendar-full
  section3:
    title: One Framework
    subtitle: Build CNFs for Existing and Future Networks
    image: ligato/ligato-front-pillar-blue-grey.svg
    buttonText: Get started
    buttonLink: "https://docs.ligato.io/en/latest/user-guide/quickstart/"
  footer:
    # Logo (from /images/logos/___)
    logo: ligato-diamond.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/ligato
      icon: github
    - link: https://ligato.slack.com
      icon: slack
    - link: https://groups.google.com/d/forum/ligato
      icon: envelope-o
    - link: https://twitter.com/ligatoProject
      icon: twitter
    bulmalogo: false
    quicklinks:
#      column1:
#        title: "Golang"
#        links:
#        - text: Golang.org
#          link: https://golang.org
#        - text: Go by Example
#          link: https://gobyexample.com/
#        - text: Hello World in Go
#          link: https://gobyexample.com/hello-world
#        - text: Our roadmap
#          link: /
#        - text: Request features
#          link: /
      column2:
        title: "Documentation"
        links:
        - text: Ligato Docs
          link: "https://docs.ligato.io/en/latest/"
        - text: Quickstart
          link: "https://docs.ligato.io/en/latest/user-guide/quickstart/"
        - text: Concepts
          link: "https://docs.ligato.io/en/latest/user-guide/concepts/"
        - text: Tutorials
          link: "https://docs.ligato.io/en/latest/tutorials/00_tutorial-setup/"
        - text: FAQ
          link: "https://docs.ligato.io/en/latest/intro/faq/"
disableKinds: ["taxonomy", "taxonomyTerm", "section"]
